// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujhfbxofcsigdwshvtrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqaGZieG9mY3NpZ2R3c2h2dHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTQ5NDYsImV4cCI6MjA2MTk3MDk0Nn0.KBukC28yXLgFiqgGqrZVwnPP0MvyJaLA3lG4k_ws--E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);